<h1>Üyelik Sözleşmesi</h1>
<p>&#8226;Sitemizden kısıtlama olmaksızın yararlanabilmek için üyelik kaydı yaparak  kullanıcı olmak gerekmektedir. Kullanıcı olabilmek için 7 yaşını doldurmuş  olmak yeterlidir.</p>
<p>&#8226;Bu sözleşmenin kabul edilip sitemize kayıt olunması durumunda şahıs sitemizin kullanıcısı olmaktadır. Hizmet ve bilgilerden yararlanma konusunda sitemizin  kullanım koşulları geçerli olacaktır. Kullanıcı tüm site kullanım kural ve  kısıtlamalarına uyacağını kabul ve taahhüt eder.</p>
<p>&#8226;Kullanıcılarımızdan, sitemize üye olurken genel kabul gören ahlaki  değerlere uygun olan bir takma ad almalarını rica ederiz.  Aksi fark edildiği durumda kullanıcıya haber verilmeksizin  kullanıcı adları ve hesapları silinebilir. Alınan takma adlardan dolayı sitemiz  bir sorumluluk kabul etmez ve sorumluluk kayıt olan kişiye aittir.</p>
<p>&#8226;Sitemizde  iki farklı takma  ad ve/veya hesap sahibi olmanız yasaktır. Tek bir hesap ile girmeniz,  dolaşmanız ve mesaj atmanıza izin verilmektedir. Bunun dışında birden fazla  üyeliği bulunan kişilerin hesapları kapatılabilir.</p>
<p>&#8226;Sitemiz, üye olurken verdiğiniz bilgilerin doğru olduğunu kabul eder. Bu  bilgileri herhangi bir kurum veya üçüncü şahıslara vermez. Gerektiği zaman  yasal mercilere bildirir.</p>
<p>&#8226;Sitemiz üyeleri diledikleri zaman kullanıcı panellerinden üyeliklerini  sonlandırabilirler. Üyelikten çıkanların forumda ve diğer bölümlerdeki mesaj ve  yorumları silinmez. Site yönetiminden silinmesi istense de sitemizin böyle  bir zorunluluğu yoktur.</p>
<p>&#8226;Sitemizdeki  hak kısıtlamaları yöneticiler tarafından değiştirilebilmektedir bu yüzden bu  yönde maddeler ilerde bu anlaşmaya eklenebilir ve kullanıcı bu maddeleri kabul  etmiş sayılır. </p>
Bu koşulları kabul ediyorsanız aşağıdaki bağlantıya tıklayarak üyelik işlemini başlatabilirsiniz.<br /><br />
<?php echo anchor('user/register','Üye olmak için tıklayınız.','class="awesome green"'); ?>